# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: 'deps(npm):'
    groups:
      typescript:
        patterns:
          - 'node-modules-inspector'
          - 'typescript'
          - 'typedoc'
          - '@types/*'
      voidzero:
        patterns:
          - 'oxfmt'
          - 'oxlint'
          - 'oxlint-tsgolint'
          - 'rolldown'
          - 'rolldown-vite'
          - 'rolldown-plugin-*'
          - 'tsdown'
          - 'vite'
          - 'vite-plugin-*'
          - 'vitest'
          - '@vitest/*'
    open-pull-requests-limit: 4

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'deps(gha):'
    groups:
      github:
        patterns:
          - 'github/*'
          - 'actions/*'
    open-pull-requests-limit: 4
